# celery-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: piyushbugmetrics/dynamic-worker-dj:latest
        command: ["celery", "-A", "core", "worker", "-l", "info"]

---
# celery-beat-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
      - name: celery-beat
        image: piyushbugmetrics/dynamic-worker-dj:latest
        command: ["celery", "-A", "core", "beat", "-l", "info"]
