# django-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: piyushbugmetrics/dynamic-worker-dj:latest
        ports:
        - containerPort: 8000
---
# django-service
apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  selector:
    app: django
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30004