FROM python:3.12.3-bookworm

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt update --fix-missing && apt install -y --no-install-recommends gcc

WORKDIR /usr/src/core

RUN python -m pip install --upgrade pip
RUN pip install pipenv --upgrade

COPY Pipfile /usr/src/core/
COPY Pipfile.lock /usr/src/core/

RUN pipenv install --deploy --system

COPY . .

ARG USERNAME=noob
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

USER $USERNAME

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]